### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by pikkoH** [Minimillius/Motor-Imagery-BCI#1]
i have downloaded your code,and add bci competition Ⅲ dataset Ⅲa,but it remind me missing the function myCSP
![image](https://github.com/Minimillius/Motor-Imagery-BCI/assets/117788248/1d5811d4-2788-4023-89ff-4294085473f7)

**Comment by Minimillius** [comment]
Missing files were added to the repository. The code should be good to go.
